spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialectm.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: username
    password: password